-- Testfoodo PostgreSQL schema for Neon.
-- The FastAPI service can create the same tables automatically when
-- AUTO_CREATE_SCHEMA=true; this file is provided for review and manual setup.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS dining_halls (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id VARCHAR(20) UNIQUE NOT NULL,
    slug VARCHAR(80) UNIQUE NOT NULL,
    name VARCHAR(160) UNIQUE NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS stations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hall_id INTEGER NOT NULL REFERENCES dining_halls(id) ON DELETE CASCADE,
    name VARCHAR(180) NOT NULL,
    CONSTRAINT uq_station_hall_name UNIQUE (hall_id, name)
);

CREATE TABLE IF NOT EXISTS foods (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    source_key VARCHAR(80) UNIQUE NOT NULL,
    name VARCHAR(250) NOT NULL,
    serving_size VARCHAR(100),
    calories DOUBLE PRECISION,
    protein_g DOUBLE PRECISION,
    carbs_g DOUBLE PRECISION,
    fat_g DOUBLE PRECISION,
    saturated_fat_g DOUBLE PRECISION,
    fiber_g DOUBLE PRECISION,
    sugar_g DOUBLE PRECISION,
    sodium_mg DOUBLE PRECISION,
    ingredients TEXT,
    source_url TEXT NOT NULL,
    nutrition_updated_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_foods_name ON foods(name);

CREATE TABLE IF NOT EXISTS food_labels (
    food_id UUID NOT NULL REFERENCES foods(id) ON DELETE CASCADE,
    name VARCHAR(80) NOT NULL,
    kind VARCHAR(20) NOT NULL CHECK (kind IN ('allergen', 'dietary', 'attribute')),
    PRIMARY KEY (food_id, name)
);

CREATE INDEX IF NOT EXISTS ix_food_labels_lookup ON food_labels(name, kind, food_id);

CREATE TABLE IF NOT EXISTS menu_availability (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    food_id UUID NOT NULL REFERENCES foods(id) ON DELETE CASCADE,
    station_id INTEGER NOT NULL REFERENCES stations(id) ON DELETE CASCADE,
    menu_date DATE NOT NULL,
    meal_period VARCHAR(20) NOT NULL CHECK (meal_period IN ('Breakfast', 'Lunch', 'Dinner')),
    source_url TEXT NOT NULL,
    scraped_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_menu_item UNIQUE (food_id, station_id, menu_date, meal_period)
);

CREATE INDEX IF NOT EXISTS ix_menu_availability_date ON menu_availability(menu_date);
CREATE INDEX IF NOT EXISTS ix_menu_availability_food ON menu_availability(food_id);
CREATE INDEX IF NOT EXISTS ix_menu_availability_station ON menu_availability(station_id);
CREATE INDEX IF NOT EXISTS ix_menu_hall_date_meal ON menu_availability(menu_date, meal_period, station_id);

CREATE TABLE IF NOT EXISTS scrape_runs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    completed_at TIMESTAMPTZ,
    status VARCHAR(20) NOT NULL DEFAULT 'running',
    dates_requested JSONB NOT NULL DEFAULT '[]'::jsonb,
    menu_items_found INTEGER NOT NULL DEFAULT 0,
    foods_refreshed INTEGER NOT NULL DEFAULT 0,
    errors JSONB NOT NULL DEFAULT '[]'::jsonb
);

CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email VARCHAR(320) UNIQUE NOT NULL,
    display_name VARCHAR(100) NOT NULL,
    timezone VARCHAR(80) NOT NULL DEFAULT 'America/New_York',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_users_email ON users(email);

CREATE TABLE IF NOT EXISTS user_credentials (
    user_id UUID PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    password_hash TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS user_sessions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash CHAR(64) UNIQUE NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS ix_user_sessions_user ON user_sessions(user_id);
CREATE INDEX IF NOT EXISTS ix_user_sessions_token ON user_sessions(token_hash);

CREATE TABLE IF NOT EXISTS user_preferences (
    user_id UUID PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    calorie_goal DOUBLE PRECISION NOT NULL DEFAULT 2200,
    protein_goal_g DOUBLE PRECISION NOT NULL DEFAULT 140,
    carbs_goal_g DOUBLE PRECISION NOT NULL DEFAULT 250,
    fat_goal_g DOUBLE PRECISION NOT NULL DEFAULT 70,
    dietary_preferences JSONB NOT NULL DEFAULT '[]'::jsonb,
    excluded_labels JSONB NOT NULL DEFAULT '[]'::jsonb,
    profile_data JSONB NOT NULL DEFAULT '{}'::jsonb,
    favorite_hall_id INTEGER REFERENCES dining_halls(id) ON DELETE SET NULL
);

ALTER TABLE user_preferences
    ADD COLUMN IF NOT EXISTS profile_data JSONB NOT NULL DEFAULT '{}'::jsonb;

CREATE TABLE IF NOT EXISTS daily_goals (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    goal_date DATE NOT NULL,
    calorie_goal DOUBLE PRECISION NOT NULL CHECK (calorie_goal > 0),
    protein_goal_g DOUBLE PRECISION NOT NULL CHECK (protein_goal_g > 0),
    carbs_goal_g DOUBLE PRECISION NOT NULL CHECK (carbs_goal_g > 0),
    fat_goal_g DOUBLE PRECISION NOT NULL CHECK (fat_goal_g > 0),
    CONSTRAINT uq_user_goal_date UNIQUE (user_id, goal_date)
);

CREATE INDEX IF NOT EXISTS ix_daily_goals_user_date ON daily_goals(user_id, goal_date);

CREATE TABLE IF NOT EXISTS food_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    food_id UUID REFERENCES foods(id) ON DELETE SET NULL,
    availability_id INTEGER REFERENCES menu_availability(id) ON DELETE SET NULL,
    food_name VARCHAR(250) NOT NULL,
    serving_size VARCHAR(100),
    servings DOUBLE PRECISION NOT NULL DEFAULT 1 CHECK (servings > 0),
    meal_type VARCHAR(30) NOT NULL DEFAULT 'Snack',
    eaten_at TIMESTAMPTZ NOT NULL,
    calories_per_serving DOUBLE PRECISION NOT NULL DEFAULT 0,
    protein_per_serving_g DOUBLE PRECISION NOT NULL DEFAULT 0,
    carbs_per_serving_g DOUBLE PRECISION NOT NULL DEFAULT 0,
    fat_per_serving_g DOUBLE PRECISION NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_food_logs_user_time ON food_logs(user_id, eaten_at DESC);

CREATE TABLE IF NOT EXISTS favorite_foods (
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    food_id UUID NOT NULL REFERENCES foods(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, food_id)
);

CREATE TABLE IF NOT EXISTS saved_meals (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name VARCHAR(120) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_saved_meals_user ON saved_meals(user_id);

CREATE TABLE IF NOT EXISTS saved_meal_items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    saved_meal_id UUID NOT NULL REFERENCES saved_meals(id) ON DELETE CASCADE,
    food_id UUID NOT NULL REFERENCES foods(id) ON DELETE CASCADE,
    servings DOUBLE PRECISION NOT NULL DEFAULT 1 CHECK (servings > 0)
);

CREATE INDEX IF NOT EXISTS ix_saved_meal_items_meal ON saved_meal_items(saved_meal_id);

INSERT INTO dining_halls (source_id, slug, name)
VALUES
    ('16', 'south-campus', 'South Campus Dining Hall'),
    ('19', 'yahentamitsi', 'Yahentamitsi Dining Hall'),
    ('51', '251-north', '251 North')
ON CONFLICT (source_id) DO UPDATE
SET slug = EXCLUDED.slug, name = EXCLUDED.name, is_active = TRUE;

